### ISSUE TITLE
Addon breaks cp for non super users

### ISSUE THREAD

**Issue by rrelmy** [jrc9designstudio/statamic-google-analytics#2]
If a non super user with cp access logs in the cp shows only this error

    ErrorException in Nav.php line 35:
    Call to a member function add() on null

1. The `configure` navigation point is only available if the user has the `super` or `users:edit` right.
2. The addon settings page is only available for super users

**Comment by jcohlmeyer** [comment]
Fix: Addon breaks cp for non super users #2
